### ISSUE TITLE
Data URI? 

### ISSUE THREAD

**Issue by streeetlamp** [VCUarts/vcubar#3]
We could look at using data-uri for images if they are small enough so we arent moving images all around 

![ays](https://cloud.githubusercontent.com/assets/1740634/4388810/23232dbe-43ef-11e4-962a-76351eb74f41.gif)

**Comment by streeetlamp** [comment]
not doing this !

**Comment by luetkemj** [comment]
![image](http://media1.giphy.com/media/9CvWZTFXyNBio/200.gif)
